Images:
  ApiServer: $(IMAGES_APISERVER)
  PersistenceAgent: $(IMAGES_PERSISTENCEAGENT)
  ScheduledWorkflow: $(IMAGES_SCHEDULEDWORKFLOW)
  MlmdEnvoy: $(IMAGES_MLMDENVOY)
  MlmdGRPC: $(IMAGES_MLMDGRPC)
  ArgoExecImage: $(IMAGES_ARGO_EXEC)
  ArgoWorkflowController: $(IMAGES_ARGO_WORKFLOWCONTROLLER)
  LauncherImage: $(IMAGES_LAUNCHER)
  DriverImage: $(IMAGES_DRIVER)
  OAuthProxy: $(IMAGES_OAUTHPROXY)
  MariaDB: $(IMAGES_MARIADB)
  RuntimeGeneric: $(IMAGES_PIPELINESRUNTIMEGENERIC)
  Toolbox: $(IMAGES_TOOLBOX)
  RHELAI: $(IMAGES_RHELAI)
Samples:
  Iris: /pipelines/iris-compiled.yaml
  Instructlab: /pipelines/instructlab.yaml
ManagedPipelinesMetadata:
  Instructlab:
    Name: "[InstructLab] LLM Training Pipeline"
    Description:
    Filepath: /pipelines/instructlab.yaml
    VersionName: "[InstructLab] LLM Training Pipeline - $(PLATFORMVERSION)"
  Iris: 
    Name: "[Demo] iris-training"
    Description: "[source code](https://github.com/opendatahub-io/data-science-pipelines/tree/master/samples/iris-sklearn) A simple pipeline to demonstrate a basic ML Training workflow"
    Filepath: /samples/iris-pipeline-compiled.yaml
    VersionName: "[Demo] iris-training - $(PLATFORMVERSION)"
DSPO:
  HealthCheck:
    Database:
      ConnectionTimeout: $(DSPO_HEALTHCHECK_DATABASE_CONNECTIONTIMEOUT)
    ObjectStore:
      ConnectionTimeout: $(DSPO_HEALTHCHECK_OBJECTSTORE_CONNECTIONTIMEOUT)
  RequeueTime: $(DSPO_REQUEUE_TIME)
  PlatformVersion: $(PLATFORMVERSION)
