apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dspipelines.io_v1alpha1_dspipeline.yaml
  - db-creds.yaml
  - artifact_script.yaml
  - storage-creds.yaml
  - ui-configmap.yaml
