apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
- ../../argo

images:
- name: quay.io/argoproj/argocli
  newName: quay.io/opendatahub/ds-pipelines-argo-server
  newTag: 3.3.10-upstream
