apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: AWS S3 Connection
stringData:
  accesskey: "minio"
  secretkey: "minio123"
type: Opaque
