apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odh-applications
resources:
- ../../base
patchesStrategicMerge:
- img_patch.yaml
images:
- name: controller
  newName: quay.io/hbelmiro/dspo
  newTag: dev-issue-495-1702651405
