name: Image push per Github Tag

run-name: Creating new tag in quay based on latest pushed tag in Github.
on:
  workflow_dispatch:
    inputs:
      target_tag:
        default: 'vx.y.z'
        description: 'DSPO Tag'
        required: true
env:
  QUAY_IMAGE_REPO: ${{ secrets.QUAY_IMAGE_REPO }}
jobs:
  copy-tag-to-quay:
    runs-on: ubuntu-latest
    if: github.repository == 'opendatahub-io/data-science-pipelines-operator'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install skopeo
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo
      - name: Login to quay.io
        shell: bash
        env:
          QUAY_ROBOT_USERNAME: ${{ secrets.QUAY_ROBOT_USERNAME }}
          QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
        run: |
         skopeo login quay.io -u ${QUAY_ROBOT_USERNAME} -p ${QUAY_ROBOT_TOKEN}
      - name: Get latest tag hash
        id: hash
        run: echo "hash=$(git rev-parse --short ${{ inputs.target_tag }} )" >> ${GITHUB_OUTPUT}
      - name: Create new tag
        shell: bash
        env:
          HASH: ${{ steps.hash.outputs.hash }}
        run: |
          skopeo copy docker://${QUAY_IMAGE_REPO}:main-${{ env.HASH }} docker://${QUAY_IMAGE_REPO}:${{ inputs.target_tag }}
      - name: Create latest tag
        shell: bash
        env:
          HASH: ${{ steps.hash.outputs.hash }}
        run: |
          skopeo copy docker://${QUAY_IMAGE_REPO}:main-${{ env.HASH }} docker://${QUAY_IMAGE_REPO}:latest
